[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
sqlx.workspace = true
redis.workspace = true
garde.workspace = true
strum.workspace = true
